CREATE TABLE llx_evr_reports (
	rowid INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	codigo INT(11) UNSIGNED NOT NULL,
	modulo VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NOT NULL DEFAULT '',
	detalle VARCHAR(255) NOT NULL DEFAULT '',
	ficheros VARCHAR(255) NOT NULL DEFAULT '',
	activo INT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (rowid)
)
ENGINE=InnoDB