CREATE TABLE llx_evr_def_permisos (
	id INT(11) NOT NULL DEFAULT '0',
	libelle VARCHAR(255) NULL DEFAULT NULL,
	module VARCHAR(64) NULL DEFAULT NULL,
	entity INT(11) NOT NULL DEFAULT '1',
	perms VARCHAR(50) NULL DEFAULT NULL,
	subperms VARCHAR(50) NULL DEFAULT NULL,
	type VARCHAR(1) NULL DEFAULT NULL,
	bydefault TINYINT(4) NULL DEFAULT '0',
	PRIMARY KEY (id, entity)
)
ENGINE=InnoDB;