<?php
$g_translations = array (
		"fr_fr" => array (
				//Common data
				"Interval" => "Interval",
				"Type" => "Type",
				"Status" => "Status",
				"Customer" => "Client",
				"Supplier" => "Fournisseur",
				"Customers" => "Clients",
				"Suppliers" => "Fournisseurs",
				"Idprof1" => "SIREN",
				"Date" => "Date",
				"Yes" => "Oui",
				"No" => "Non",
				"Total Et" => "Total HT",
				"Total Ttc" => "Total",
				"Vat" => "TVA",
				"VAT" => "TVA",
				"Price Et" => "Prix HT",
				"Prix It" => "Total",
				"Total It" => "Total",
				"Average" => "Moyen",
				"Paid" => "Paye",
				"Show" => "Montrer",
				"Products" => "Produits",
				"Services" => "Services",
				"Description" => "Description",
				"Warehouse" => "Entrepot",
				"Product" => "Produit",
				"Service" => "Service",
				"Product/Service" => "Produit/Service",
				"Category" => "Categorie",
				"Customer Category" => "Categorie de clients",
				"Product Category" => "Categorie de produit",
				"Reference" => "Reference",
				"Quantity" => "Quantite",
				"Qty." => "Qty.",
				"Qty" => "Qty.",
				"Avg. Price" => "Prix moyen",
				"Name" => "Nom",
				"Order" => "Commande",
				"Label" => "Etiquette",
				"Canceled" => "Annule",
				"Envoyed" => "Envoye",
				"Processed" => "Traite",
				"Invoiced" => "Facture",
				"Hide" => "Cacher",
				"Sales representative" => "Representant des ventes",
				"Nom" => "Nom",
				"Adress" => "Adresse",
				"City" => "Ville",
				"Phone" => "Telephone",
				"Fax" => "Fax",
				"Email" => "E-Mail",
				"First Name" => "Prenom",
				"Last Name" => "Nom",
				"Company" => "Company",
				"Post" => "Poste",
				"Mobile" => "Mobile",
				"User" => "Utilisateur",
				"Hours" => "Heures",				
				"Sale Price" => "Prix de vente",
				"Buy Price" => "Acheter prix",
				"Margin" => "Marge",

				//Months
				"Month" => "Mois",
				"January" => "Janvier",
				"February" => "Fevrier",
				"March" => "Mars",
				"April" => "Avril",
				"May" => "Mai",
				"June" => "Juin",
				"July" => "Juillet",
				"August" => "Aout",
				"September" => "Septembre",
				"October" => "Octobre",
				"November" => "Novembre",
				"December" => "Decembre",
				"No Data Matched Your Criteria" => "Pas de donnees",
				"Year" => "Anne",				

				//Invoices
				"Customers invoices" => "Factures aux clients",
				"Sales summary" => "Sommaire des ventes",
				"Supplier invoices" => "Factures des fournisseurs",
				"Purchases summary" => "Sommaire des achats",
				"Sales Tax detail" => "Ventilation TVA ventes",
				"Purchases Tax detail" => "Ventilation TVA achats",
				"Margin By Customer" => "Marge par client",
				"Margin By Sales Representative" => "Marge par representant des ventes",
				"Balance" => "Bilan",
				"Income By Customer" => "Recette par client",
				"Sales By Sales Representative" => "Ventes par representant des ventes",
				"Invoice" => "Facture",
				"Invoices" => "Factures",
				"Standard" => "Standard",
				"Replacement" => "Replacement",
				"Credit Note" => "Note de credit",
				"Deposit" => "d'acompte",
				"Proform" => "Proforma",
				"Draft" => "Brouillon",
				"Validated" => "Valide",
				"Paid (total or parcial)" => "Paied (total ou partiel)",
				"Abandoned" => "Abandonne",
				"Charged" => "Charge",
				"Facture" => "Facture",
				"Total Invoiced" => "Total facture",
				"Average Invoice" => "Moyen par facture",
				"Income" => "Recettes",
				"Expense" => "Depenses",
				
				//Products
				"Products list" => "Liste des produits",
				"Products Stocks" => "Stocks de produits",
				"Stock alerts" => "Alertes stock",
				"Products sales" => "Ventes de produits",
				"Sales details" => "Ventilation des ventes",
				"Undelivered products" => "Produits pendants",
				"Ordered products" => "Produits commandes",
				"Stock Alert" => "Alertes stock",
				"Margin By Product" => "Marge par produit",
				"Stocktotal" => "Total",
				"Customer Code" => "Code client",
				"Qty Ordered" => "Qty. Demande",
				"Qty Shipped" => "Qty. Envoye",
				"Pending" => "Pendant",
				
				//Propals
				"Customer proposals" => "Propales aux clients",
				"Opened" => "Ouvert",
				"Signed" => "Signe",
				"Not signed" => "Non signe",
				"Billed" => "Facture",
				
				//Orders
				"Customer orders" => "Commandes des clients",
				"Suppliers Orders" => "Commandes aux fournisseurs",
				"Approved" => "Approuve",
				"In process" => "En cours",
				"Partially received" => "Reçue partiellement",
				"Received" => "Reçu",
				"Annuled" => "Annule",
				"Not received" => "Pas reçu",
				"Rejected" => "Rejete",

				//Contracts
				"Active Contracts" => "Contrats actifs",
				"Expiring Contracts" => "Contrats expirant",
				"Start Prev" => "Prevue mise",
				"Start" => "Effective mise",
				"End Prev" => "Prevue fin",
				"End" => "Effective fin",
				"Active" => "Actif",
				"Inactive" => "Inactif",
				"Closed" => "Ferme",
				
				//Thirds
				"List of Third Parties" => "Liste des tiers",
				"List of contacts" => "Liste des contacts",

				//Projects
				"Project" => "Projet",
				"Task" => "Tache",
				"List of projects" => "Liste des projets",

				//Ecommerce
				"Customer Ecommerce Orders" => "Commandes clients Ecommerce",
				"Ecommerce Sales Tax Detail" => "Ventilation TVA ventes Ecommerce",
				"Ecommerce Customers invoices" => "Factures Clients Ecommerce",
				"Product Sales Ecommerce" => "Ventes des produits Ecommerce",
				"Ecommerce Sales Summary" => "Sommaire des ventes Ecommerce",
				
			),
		"es_es" => array (
				//Common data
				"Interval" => "Intervalo",
				"Type" => "Tipo",
				"Status" => "Estado",
				"Customer" => "Cliente",
				"Supplier" => "Proveedor",
				"Customers" => "Clientes",
				"Suppliers" => "Proveedores",
				"Idprof1" => "CIF/NIF",
				"Date" => "Fecha",
				"Yes" => "Si",
				"No" => "No",
				"Total Et" => "Base imp.",
				"Total Ttc" => "Total",
				"Vat" => "IVA",
				"VAT" => "IVA",
				"Price Et" => "Base imp.",
				"Prix It" => "Total",
				"Total It" => "Total",
				"Average" => "Media",
				"Paid" => "Pagada",
				"Show" => "Mostrar",
				"Products" => "Productos",
				"Services" => "Servicios",
				"Description" => "Descripcion",
				"Warehouse" => "Almacen",
				"Product" => "Producto",
				"Service" => "Servicio",
				"Product/Service" => "Producto/Servicio",
				"Category" => "Categoria",
				"Customer Category" => "Categoria de cliente",
				"Product Category" => "Categoria de producto",
				"Reference" => "Referencia",
				"Quantity" => "Cantidad",
				"Qty." => "Cant.",
				"Qty" => "Cant.",
				"Avg. Price" => "Precio medio",
				"Name" => "Nombre",
				"Order" => "Pedido",
				"Label" => "Etiqueta",
				"Canceled" => "Cancelado",
				"Envoyed" => "Enviado",
				"Processed" => "Procesado",
				"Invoiced" => "Facturado",
				"Hide" => "Ocultar",
				"Sales representative" => "Comercial",
				"Nom" => "Nombre",
				"Adress" => "Direccion",
				"City" => "Poblacion",
				"Phone" => "Telefono",
				"Fax" => "Fax",
				"Email" => "E-Mail",
				"First Name" => "Nombre",
				"Last Name" => "Apellidos",
				"Company" => "Empresa",
				"Post" => "Puesto",
				"Mobile" => "Movil",
				"Page pageno()" => "Pagina pageno()",
				"User" => "Usuario",
				"Hours" => "Horas",	
				"Sale Price" => "Precio de venta",
				"Buy Price" => "Precio de compra",
				"Margin" => "Margen",			
				
				//Months
				"Month" => "Mes",
				"January" => "Enero",
				"February" => "Febrero",
				"March" => "Marzo",
				"April" => "Abril",
				"May" => "Mayo",
				"June" => "Junio",
				"July" => "Julio",
				"August" => "Agosto",
				"September" => "Septiembre",
				"October" => "Octubre",
				"November" => "Noviembre",
				"December" => "Diciembre",
				"No Data Matched Your Criteria" => "No hay datos disponibles",
				"Year" => "Año",
				
				//Invoices
				"Customers invoices" => "Facturas a clientes",
				"Sales summary" => "Resumen de ventas",
				"Supplier invoices" => "Facturas de proveedores",
				"Purchases summary" => "Resumen de compras",
				"Sales Tax detail" => "Desglose IVA ventas",
				"Purchases Tax detail" => "Desglose IVA compras",
				"Margin By Customer" => "Margen por cliente",
				"Margin By Sales Representative" => "Margen por comercial",
				"Balance" => "Balance",
				"Income By Customer" => "Ingresos por cliente",
				"Sales By Sales Representative" => "Ventas por comercial",
				"Invoice" => "Factura",
				"Invoices" => "Facturas",
				"Standard" => "Estandard",
				"Replacement" => "Rectificativa",
				"Credit Note" => "Abono",
				"Deposit" => "Anticipo",
				"Proform" => "Proforma",
				"Draft" => "Borrador",
				"Validated" => "Validada",
				"Paid (total or parcial)" => "Pagada (total o parcial)",
				"Abandoned" => "Abandonada",
				"Charged" => "Cobrada",
				"Facture" => "Factura",
				"Total Invoiced" => "Total facturado",
				"Average Invoice" => "Media por factura",
				"Income" => "Ingresos",
				"Expense" => "Gastos",
				
				//Products
				"Products list" => "Listado de productos",
				"Products Stocks" => "Stocks de productos",
				"Stock alerts" => "Alertas de stock",
				"Products sales" => "Ventas de productos",
				"Sales details" => "Desglose de ventas",
				"Undelivered products" => "Productos por enviar",
				"Ordered products" => "Productos pedidos",
				"Stock Alert" => "Alerta de stock",
				"Margin By Product" => "Margen por producto",
				"Stocktotal" => "Total",
				"Customer Code" => "Codigo Cliente",
				"Qty Ordered" => "Cant. Pedida",
				"Qty Shipped" => "Cant. Enviada",
				"Pending" => "Pendiente",
				
				//Propals
				"Customer proposals" => "Presupuestos a clientes",
				"Opened" => "Abierto",
				"Signed" => "Firmado",
				"Not signed" => "No firmado",
				"Billed" => "Facturado",
				
				//Orders
				"Customer orders" => "Pedidos de clientes",
				"Suppliers Orders" => "Pedidos a proveedores",
				"Approved" => "Aprobado",
				"In process" => "En proceso",
				"Partially received" => "Recibido parcialmente",
				"Received" => "Recibido",
				"Annuled" => "Anulado",
				"Not received" => "No recibido",
				"Rejected" => "Rechazado",

				//Contracts
				"Active Contracts" => "Contratos activos",
				"Expiring Contracts" => "Contratos a expirar",
				"Start Prev" => "Inicio previsto",
				"Start" => "Inicio real",
				"End Prev" => "Fin previsto",
				"End" => "Fin real",
				"Active" => "Activo",
				"Inactive" => "Inactivo",
				"Closed" => "Cerrado",
				
				//Thirds
				"List of Third Parties" => "Listado de terceros",
				"List of contacts" => "Listado de contactos",

				//Projects
				"Project" => "Proyecto",
				"Task" => "Tarea",
				"List of projects" => "Listado de proyectos",

				//Ecommerce
				"Customer Ecommerce Orders" => "Pedidos Clientes Ecommerce",
				"Ecommerce Sales Tax Detail" => "Desglose IVA ventas Ecommerce",
				"Ecommerce Customers invoices" => "Facturas Clientes Ecommerce",
				"Product Sales Ecommerce" => "Venta productos Ecommerce",
				"Ecommerce Sales Summary" => "Resumen ventas Ecommerce",		
			)
		);
/*
$g_report_desc = array ( "fr_fr" => array (
		"tut2_loanhistory.xml" =>
'
La <b>Report Du Emplacement Histoire</b> produit une liste des filmes bourree du libraire groupee par membre.
<p>
Il montre le suivant :-
<p>
1. 
 of adding a date range criteria by reporting on films that have been borrowed between the specified dates. It also demonstrates the use of setting date range defaults.
<p>
2. use of a LIST type criteria item
<p>
3. conditional assignment by displaying "UNRETURNED" in the return date column instead of a normal blank
'
			)
		);
		*/
?>
